name: snicker_shoes
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/Icons/shoes.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/Icons/shoes.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/Icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans.ttf
        - asset: assets/fonts/opensans-italic.ttf
          weight: 600
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 600
